/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ldmbtiolpnklvlscxied"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbWJ0aW9scG5rbHZsc2N4aWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2ODU1NjUsImV4cCI6MjA4MjI2MTU2NX0.tieTjckpinBWc-PKsV9omJOpY-buN1owHUaOh-x8zoQ"